reponder_perguntas_de_notas_fiscais:
  description: >
    Analise a pergunta do usuário sobre dados de notas fiscais e gere código Python usando pandas 
    para responder à questão: {pergunta}
    
    Os dados das notas fiscais estão disponíveis em um DataFrame chamado 'df'.
    
    Processo:
    1. Desenvolva código Python/pandas para processar o DataFrame 'df' e responder à pergunta
    2. Não gere codigo que retorne em uma variavel, sempre execute diretamente.
    3. Execute o código usando a tool 'execute_csv_query', informa no parametro csv_name o nome do arquivo selecionado {csv_name}
    4. Guarde a saida da ferramenta 'execute_csv_query' para ser usada na resposta final
    5. Exiba o código gerado e a saida da ferramenta 'execute_csv_query' em formato de tabela.
    6. Apresente os resultados de forma clara e organizada
    

    Importante: Seja direto e objetivo, evitando frases como "Vou executar o código", 
    "O resultado é:", "I now know the answer", etc.
    
  expected_output: >
    Forneça uma resposta estruturada contendo:
    
    1. Uma resposta amigável e clara que explique os resultados encontrados.
    2. O código Python/pandas utilizado para processar os dados, sempre mostre o codigo gerado.
    3. A output  de 'execute_csv_query' que foi armazenado, SEMPRE mostre essa etapa, não a omita.
    
                 
  agent: analista_dados
  

